### ISSUE TITLE
Allow JSONClient to throw timeout exception

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-core#107]
JSONClient eagerly catches any exceptions and ends up throwing a RuntimeException, attempting to parse a JSON response into a known Hoist exception along the way:

https://github.com/xh/hoist-core/blob/develop/src/main/groovy/io/xh/hoist/http/JSONClient.groovy#L106

I would like to support the case where we handle SocketTimeoutExceptions as routine so we don't get giant stacktrackes. This could either be a built-in case handled by this class, or we could reconsider this general exception approach to allow users of JSONClient more control over how it catches and throws.

**Comment by lbwexler** [comment]
took a look at this and definitely understand the case you are trying to handle.  A couple of quick thoughts:

+ I don't think socket timeouts should be 'routine', with our current understanding of routine exceptions.  However, I can see why you would almost never want a giant stacktrace resulting from a failed HTTP request.  It seems to me that we need to ask ourselves -- when *do* we want a giant stacktrace in our logs?  Why aren't we more aggressively putting things elsewhere in our default exception handling.

+ Right now, the "cause" of the exception would be the underlying SocketTimeout, but I agree that that is not really optimal for the end-user. I can't recall any good reason right now for not returning the underlying exception and will look at returning it.

**Comment by amcclain** [comment]
Thanks for looking at this - agree with you on both points re. this not really being a "routine" exception but also us very rarely (if ever) wanting large stacktraces in our primary logs.

My thinking around "routine" was, loosely, that these exceptions didn't represent a programming error, or a fatal / unrecoverable condition, but were likely transient and could in some applications occur with some amount of frequency.  But I can see and agree how that's still not quite how we wanted to define routine, which is maybe more "exceptions that we might deliberately or commonly throw as part of a standard validation or other process." 

I am pretty sure this arose from me looking to troubleshoot a client app that was repeatedly timing out calling a back-end data source - the logs at that point were almost unusable due to the volume of Runtime exceptions and the length of the traces.  

Appreciate any help with it - ATM
