### ISSUE TITLE
Remove "local" default for xhTheme preference

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-core#126]
I don't see any reason why the user's choice of theme should not follow them around from machine to machine. We had a client request to do the same.

(We currently default this pref to local in Bootstrap, which causes the server to output a warning if the pref has been modified within the app to be non-local.)

**Comment by lbwexler** [comment]
Happy to do this, but the thought does occur to me that there is a bit of an asymmetry in the cost of being wrong for any user here:  If a user wants multiple settings per client and we have local =false, they will need to fix the problem *every* time they switch device.

On the other hand, if the user wants single settings per client and we have local= true, they need to just make the setting once per client.

**Comment by lbwexler** [comment]
Not to beat a dead horse on this, but I do easily imagine wanting one theme on my phone, and another theme on my desktop.
