### ISSUE TITLE
Build process 

### ISSUE THREAD

**Issue by ConstantineGochev** [xh/hoist-core#162]
Hi,
I am interested in your app and would love to  build and run both the back end and the front end. Can you provide a more detailed build process for running everything manually without CI ? Thanks

**Comment by amcclain** [comment]
Hi @ConstantineGochev - thanks for the comment.  I see that you've closed it today, but we do appreciate your interest. 

While we have our repos set to public and use an open license, our toolkit is intended for our use within our consulting practice / clients, typically enterprise-level finance shops for whom we build custom webapps.

Feel free to reach out via my email, available off of my GH profile.
