### ISSUE TITLE
Add built-in status Checks

### ISSUE THREAD

**Issue by lbwexler** [xh/hoist-core#235]
Would be great if Hoist Apps came out-of-the-box with some basic status checks,  to illustrate the concept and indicate that app and status check system functioning correctly

**Comment by amcclain** [comment]
Some ideas from Toolbox:
* Current memory usage, as a percentage of Xmx
* Longest page load in past n minutes, as per activity tracking

Could also consider:
* Something to explicitly test/exercise primary database connection
* JDBC connection pool stats, if we can figure out how to get them
* A look at new built-in health status checks provided by Grails5/spring-actuator (more of a research project - I would not block this ticket on understanding what we can do here, but interesting to look at some point - see https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html#actuator.endpoints.health)

**Comment by lbwexler** [comment]
Also: 

LDAP Service is responding

**Comment by lbwexler** [comment]
Jacob H already completed this.  Score!
