### ISSUE TITLE
ClientErrorService internal queuing masks exact time of error reports

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-core#278]
We had an issue where a client error report clearly had a delayed timestamp - testing more closely, we confirmed that while the service sets an immediate dateCreated time on the in-memory map representation of the error, that gets overwritten when the error is persisted on a delayed schedule to the backing domain object.

https://github.com/xh/hoist-core/blob/3ffc7fa52dad4ea56a6cb4e28640b7ed56925fb1/grails-app/services/io/xh/hoist/clienterror/ClientErrorService.groovy#L79

Can verify by turning on debug logging for the server and triggering an error - log will show time error received and queued, but error as persisted to DB / visible in viewer will show time persisted, which can vary by the configured debounce interval - up to two minutes by default.

This is a real impediment to fine-grained track of errors / correlation with logs.

Ideally we could get the dateCreated to work so we can fix this without having to coordinate a DB schema change across all deployed apps (i.e. without adding a new custom field to the domain object)

**Comment by lbwexler** [comment]
Fixed here -- great find.

https://github.com/xh/hoist-core/commit/f662fbb0e7c3c9c642daf5c6ef7aed10e3974c2c
