### ISSUE TITLE
Support overriding app configs with instance configs

### ISSUE THREAD

**Issue by haynesjm42** [xh/hoist-core#317]
I would like to be able to override any app config value with an instance config. 

Primary use-case here is for local development when also running an api used by the app locally and needing a config value for the api url to point to localhost. Because we generally use a shared dev db for local development we usually need to override this in code or come up with some other convention for handling this, otherwise we can cause issues for other devs (or the deployed dev environment) if we change the actual db config value.

**Comment by amcclain** [comment]
This just came up for @jskupsik and I, where we wanted to make our configs related to email filtering potentially a bit stronger, so we could ensure that a filter was always in place for our QA and Dev environments, even after re-sync'ing our database from prod.

The main complexity IMO is floating the fact that a config has been overwritten up to the admin console, where you would go to check and attempt to change the value of a config if you needed to adjust or troubleshoot some behavior. We'd want to make that quite clear, including showing the overridden value to admins (except for pwd configs). We could still allow editing the databased value, but the admin needs to know it wouldn't have any effect on that instance.

I don't think that's a huge change - a bit of additional metadata in the admin config listing that zips through the configs and checks if instanceConfigs exist for any of them.

I think it would be overkill, but you could imagine an admin under some circumstances wanting the ability to say "I see that this has an instance override but I really need to change it and the app should respect my databased value instead." That could be supported by some flag or meta-config that forced the system to behave one way or another, but again - that sounds like a step too far for now.

Finally, there's a chance this could play into our client project around reading values from Secret Server.  Let's see if we could get this done.

**Comment by amcclain** [comment]
(PS - Jakub easily handled our particular case by writing some extra conditions around the app-level code that was sending emails, requiring a filter for any non-Production environment. But still, this could have been another option that would apply more generally, including to any mails sent from Hoist code)
