### ISSUE TITLE
Add ability to mark a service as critical, where failure to init should throw app startup

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-core#326]

**Comment by lbwexler** [comment]
interesting -- would love to hear to hear more about this.

You could always write a tiny bit of custom code in bootstrap for the time being -- at the end of the service init call in question, check if it was actually initialized and throw there,  That will stop startup in its tracks!

**Comment by amcclain** [comment]
Hi - thanks for looking - and, yes, that's exactly what we did. We can close this ticket, but I had added it thinking about the new service-layer metadata we've added in the multi-instance branch with the status maps. Wondering if this would fit into that somehow, but as always it's difficult to know how to label / describe in a general way. 

I'll close it now, having put the idea out there in our minds in case something comes up.

```groovy
BaseService.parallelInit([upgradeService], 2 * MINUTES)
if (!upgradeService.initialized) {
    throw new RuntimeException("Failed to complete required upgrades - will not start")
}
```
