### ISSUE TITLE
`EmailService.sendEmail()` should support empty/falsey `attachments` param

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-core#349]
The current `EmailService.sendEmail()` impl triggers multipart handling if the incoming params include an `attachments` key at all, even if null or falsey:

https://github.com/xh/hoist-core/blob/2fbd3e82aa2b5ac7894574c3daa8379c4e32d3f5/grails-app/services/io/xh/hoist/email/EmailService.groovy#L87

This can trip up calling code that might sometimes have attachments but other times not - such a caller might reasonably expect that passing `attachments: null` or `attachments: []` would function the same as omitting the key entirely. 

Unclear why we are checking `arg.containsKey` here vs. looking for a truthy value - @lbwexler do you have any recollection of it?

**Comment by lbwexler** [comment]
I can't recall -- honestly, it may have been a  attempt to mirror the previous line of code, which may have been written the way it was to allow a default of either true or false.  And so generally it was just  written with the intention of avoiding a different type of bug.

I would be favor of having both lines changed to simple truthy checks.
