### ISSUE TITLE
`EmailService` generates jumbled-looking subjects if non-prod and/or with overrides

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-core#350]
Sending email with subject "My Email Subject" to recipient "user@testcompany.com" in non-prod TEST env with the `xhEmailOverride` config active yields a mail with the subject:

"My Email Subject [TEST] (for [user@testcompany.com])"

Quite a few different braces and parens in such a small string, and would fare poorly with a large original recipient list.

Could we better consolidate and made consistent the modifications here?  E.g. I would prefer something like:

My Email Subject [TEST, for user@testcompany.com]
My Email Subject [TEST, redirected from user@testcompany.com]
My Email Subject [TEST, redirected from 4 recipients]

Not sure what the best way to summarize the recipient override is - don't know that "redirected from" is really correct. Main thing though is to get all the system-appended info within a single set of wrapping [] and to ensure that we handle a large `to` list OK.

**Comment by lbwexler** [comment]
Wow -- went way too deep down this rabbit hole -- but there was nothing to do but get through it. :-)
