### ISSUE TITLE
Role Services should handle or disallow roles with dots

### ISSUE THREAD

**Issue by cnrudd** [xh/hoist-core#370]
I discovered that I am allowed to create a role named:

"microapp.tab.editor"

but I cannot delete it.

The UI sends the complete name string down when creating the role, "microapp.tab.editor" and the role gets created with the complete name.

But when I call delete in the UI, the UI sends the complete string down as part of the URL, and this time the grails controllers only keep the first part:  "microapp".

So, the delete method in DefaultRoleUpdateService throws a "cannot call delete on null" error.

We should either allow dots in names and support them in all operations, or not allow creating roles with dots in their names.

**Comment by amcclain** [comment]
That seems like a straight bug to me - we should be passing the role name as a param.  If we were using a numeric ID, sure, we could put it in the URL path as we are doing, but given the choice to use a string we see that can break. Good catch!
