### ISSUE TITLE
lastUpdated inconsistently rounded 

### ISSUE THREAD

**Issue by lbwexler** [xh/hoist-core#423]
Sometimes `lastUpdated` is returned with millisecond precision, and sometimes rounded to the second.  

Easily reproduced on MySql with Toolbox when doing updates with RestController and JsonBlobService.  The `update` typically returns the Blob with millisecond precision, but subsequent listing, will return the same value rounded to the second.

**Comment by amcclain** [comment]
@lbwexler - it sounds like the column in your local database might be of type `datetime(0)` - that's second precision. On my local DB and deployed toolbox DBs, we see `datetime(6)` - microsecond precision, and I cannot replicate the issue.  

I'm pretty confident that is how GORM will auto-create the schema - can you check your local DB to confirm? 

<img width="1191" alt="Screenshot 2024-12-20 at 7 20 58 AM" src="https://github.com/user-attachments/assets/d8e09257-3d9e-4f48-8c7d-c5aa33f8223b" />

Not sure how your schema ended up in that state - potentially manually created or adjusted at some point in the past?

**Comment by lbwexler** [comment]
Eureka -- that is indeed the state of several (but not all) of my datetime columns!

**Comment by lbwexler** [comment]
BUT -- look here -- SYBASE, for example, only seems to store datetimes down to 1/300 of a second -- NOT a full millisecond.  So my strong guess is that this is *still* going to be an issue in general for code that we write that compares a ms timestamp before and after its round-tripping in the DB.

**Comment by lbwexler** [comment]
I am going to close this, as I don't think there is an actionable bug here, but we do need to be *very* careful about storing timestamps that we generate in javascript and java, and expecting to round-trip them in the DB and get back exact values.

Disappointing -- surprised this has not bitten us before.  I suppose if we really want to get the accuracy we could use the datetime2 (7) or a long to store a timestamp,

**Comment by amcclain** [comment]
We should absolutely be using `datetime2` for all Date/Instant columns in SQL server world.  This should be the default assuming the correct dialect is specified - you can see the `SQLServer2008Dialect` (and later) map `Types.TIMESTAMP` onto `datetime2`.  

https://github.com/hibernate/hibernate-orm/blob/d7e8a69df5981cd8ad93c6819799c4cbca0b2e70/hibernate-core/src/main/java/org/hibernate/dialect/SQLServer2008Dialect.java#L29

Java `Date` is mapped to that `TIMESTAMP` type here: 

https://github.com/hibernate/hibernate-orm/blob/d7e8a69df5981cd8ad93c6819799c4cbca0b2e70/hibernate-core/src/main/java/org/hibernate/type/descriptor/sql/JdbcTypeJavaClassMappings.java#L131
