### ISSUE TITLE
Upgrade to Grails 5.0/JDK11

### ISSUE THREAD

**Issue by lbwexler** [xh/hoist-core#84]

**Comment by pauldelano** [comment]
See code in grails4Java11 branch in hoist-core and toolbox.

Upgrade steps:
--------------
* Upgrade to Java 11(+?) using Homebrew on Mac
brew update
brew tap homebrew/cask-versions
brew cask info java11 # For Java 11 
brew cask info java # For lastest version
brew cask install java11  # Install Java 11 
# brew cask install java  # Install latest version

* In Intellij:
Add the Java 11 SDK: Project Settings / SDKs / (+ Add)
Select the Java 11 SDK to be used: Project Settings / Project / Project SDK
Set Project language level to 11?
Set bytecode level to Java 8: Preferences / Build, Execution, Deployment / Compiler / Java Compiler Project byptecode version: 8

Note: Don't change the Intellij runtime to Java 11. That is not recommended.
https://intellij-support.jetbrains.com/hc/en-us/articles/206544879-Selecting-the-JDK-version-the-IDE-will-run-under

* Grails update: sdk install grails
Select 4.0.1 at install to be the current. Or relink /Users/pauld/.sdkman/candidates/grails/current to 4.0.1 or the 3.x version.


Install Hoist Toolbox:
----------------------
* Clone repos:
git clone hoist-core, hoist-react and toolbox.

* Checkout grails4Java11 branch in hoist-core and toolbox:
git checkout -b grails4Java11 origin/grails4Java11

* Copy from toolbox to top level wrapper directory:
gradlew
gradlew.bat

* Create top level settings.gradle file with:
include "toolbox", "hoist-core"

**Comment by pauldelano** [comment]
TODO:

* Fix logging in LoggingUtils
logback.groovy:
Removed LogUtils initialization.
Added simple console logging.

* Fix missing appName, appCode, appVersion
https://objectcomputing.com/news/2017/04/02/add-build-info-your-project

* Resolve missing caches in cache mgmt.

* Fix log file missing error
17:56:20.668 [http-nio-8088-exec-8] ERROR StackTrace - Full Stack Trace:
java.io.FileNotFoundException: /private/var/folders/2j/h0_60kw541zbp7qwgkmgqjjm0000gn/T/tomcat.8416885624830517408.8088/logs/null-logs
	at io.xh.hoist.admin.LogViewerAdminController.listFiles(LogViewerAdminController.groovy:25)

* Fix Build issues with build.gradle publications:
```
 // TAR distro with both the Grails WAR + client-side assets.
//        appWarAndClientAssets(MavenPublication) {
//            artifactId appCode + '-all'
//            artifact appWarAndClientAssetsDistTar
//        }
        // TAR distro with client-side assets only.
//        clientAssets(MavenPublication) {
//            artifactId appCode + '-client-assets'
//            artifact clientAssetsDistTar
//        }
```

* HoistUser @CompileStatic gives error:
Couldn't find trait helper classes on compile classpath!

* Improve CORS configuration in application.groovy:
```
    grails {
        cors {
            enabled = true
            allowCredentials = true
            allowedOrigins = ['http://localhost:3000']
        }
```

* Check @Transactional coverage
