### ISSUE TITLE
Better styling for tree grids in Excel exports

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-core#94]
Excel exports for tree grids include the hierarchy in the form of expand/collapse group buttons, but the default Excel table styling does not make it clear which level a row is at.  (Instead it uses the banded rows throughout).

Client asks if its possible to make the export styling more clear w.r.t. different levels in the tree.

**Comment by TomTirapani** [comment]
I figured out how to get POI to set row background color, and used that to alternate the table colors based on tree depth.

<img width="341" alt="Screenshot 2020-04-22 at 12 56 18" src="https://user-images.githubusercontent.com/3017757/79978973-b2ed1a00-8498-11ea-9896-65de0e824ac9.png">

We can discuss of this helps improve readability, or if a different approach could be more usable.

PR here: https://github.com/xh/hoist-core/pull/135

**Comment by TomTirapani** [comment]
Here is an alternate coloring approach that blends between blue and white based on tree depth:

<img width="329" alt="Screenshot 2020-04-22 at 13 42 59" src="https://user-images.githubusercontent.com/3017757/79983107-33167e00-849f-11ea-8fa7-58a78fcf11c0.png">

Concern here is it that it the color distinction may become insignificant if your tree has many levels

**Comment by lbwexler** [comment]
Hi Tom -- I think the alternating is more confusing -- like the blending idea alot!! 

Seems like you could start the root depth a bit darker.  Am all for taking this change and closing this ticket.
