### ISSUE TITLE
Well-handled Validation Exceptions should be logged or tracked

### ISSUE THREAD

**Issue by lbwexler** [xh/hoist-core#95]
Right now, if a user gets an expected validation error using the preference editor, we track it as a an error, with full notifications and reporting.

This is an "Expected" exception, being used to communicate between the client and the server.    It should not trigger any logging.

We should generally audit our validation code like this, to ensure we aren't causing extra noise and consternation in our notification channels.

**Comment by peterjcoffman** [comment]
When should a ValidationException be treated as an error? Should we default to treating a ValidationException as an error and disable logging when it is expected, e.g. when editing preferences, or should the default be to treat them as routine?

**Comment by lbwexler** [comment]
peter and I discussed and I gave him some more context

**Comment by lbwexler** [comment]
👍
