### ISSUE TITLE
Standard config to disable impersonation app-wide

### ISSUE THREAD

**Issue by amcclain** [xh/hoist-core#96]
Certain apps might not wish to support Hoist's standard mechanism for impersonation. It might not be desirable or make sense from a business perspective, or the JS client might be directly calling and authenticating to remote APIs which do not support impersonation, making the Hoist-level impersonation misleading/incorrect.

We could turn off impersonation in these cases to avoid confusion. A likely option is a new `xhEnableImpersonation` config - added in hoist-core Bootstrap and referenced on both server and client. 

It's possible a config might seem too lightweight (i.e. it could be turned on/off), and maybe we really want to have a hard in-code switch. But I would propose the config to start unless we thought this was a real concern.

**Comment by lbwexler** [comment]
I think this is a good idea.  Could imagine leaving this off by default, and generally having it live in an off state in production environments.

**Comment by amcclain** [comment]
Agree on having the client-side impersonation method just return quietly with a console warning if disabled. 

Happy if we get this done - it's not a big one but provides a nice extra level of control over impersonation and communicates how seriously we take it. 👍
